# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40c668e65624b0f0a1d62d2d834bfaca92150cab11a511208c71a21d7bf4477c34c3dbddef17c0938a7537acc488b31588628c3d9a3c0bcb93d6a26578976efd

test:
  secret_key_base: 87c7557a5aaedc00080e50ea728033c3f6c638b04b1b4fcba0b638368ddb1a74b4107a00b8b02bfe03e81baec6db347894275fbb93646313e34293c7b9174508

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
